select * from admins;
select * from assignments;
select * from classes;
select * from enrollment;
select * from marks;
select * from notifications;
select * from schedule;
select * from students;
select * from teachers;